	@Override
	public void handleTrapNotification(final TrapNotification message) {
		try {
			CompletableFuture.supplyAsync(message::call, m_syslogConnectionExecutor)
				.thenAcceptAsync(proc -> proc.call(), m_syslogProcessorExecutor);
		} catch (Throwable e) {
			LOG.error("Task execution failed in {}", this.getClass().getSimpleName(), e);
		}
	}

