    protected void validateInternal(Validator validator, Object itemId, Object value, ValidationResult result) {
        try {
            validator.validate(value);
        } catch (Validator.InvalidValueException ex) {
            result.add(itemId, ex);
        }
    }

