    protected void runTest() throws Throwable {
        try {
            super.runTest();
        } catch (Throwable t) {
            m_failure = true;
            throw t;
        }

    }

