    public static void main(String[] args) {
        try {
            log("starting");
            execute();
        } catch (Throwable t) {
            log("an exception was caught!", t);
        }
    }

