    /**
     * <p>afterPropertiesSet</p>
     *
     * @throws java.lang.Exception if any.
     */
    public void afterPropertiesSet() throws Exception {
        DataSourceFactory.init();
        Vault.setDataSource(DataSourceFactory.getInstance()); // Fix for Bug 4117
    }

