    protected void tearDown() throws Exception {
        assertTrue("Unexpected Warnings in Log", MockUtil.noWarningsOrHigherLogged());
        super.tearDown();
    }

