    @Test
    public void testSequence() throws Exception {
        
        
        TaskBuilder<String, String> seq = TaskBuilders.seq(TaskBuilders.compute(toInt()))
          .seq(TaskBuilders.compute(add(3)))
          .seq(TaskBuilders.compute(add(5)))
          .seq(TaskBuilders.compute(toStr()))
          .builder();
        
        Task<String, String> task = seq.buildTask(m_executor);
        
        task.start("0");
        
        assertEquals("8", task.waitFor());
        
    }

