    public InvalidDataSourceException(final Throwable cause) {
        super(cause);
    }

