    protected void tearDown() throws Exception {
        m_proxy.stop();
        
        assertTrue("Unexpected WARN or ERROR msgs in Log!", MockUtil.noWarningsOrHigherLogged());
        MockUtil.println("------------ End Test "+getName()+" --------------------------");

    }

