    // NOTE: we retry server stop because of a concurrency issue inside Jetty that is not
    // easily solvable.
    public synchronized void stop() throws Exception {
        LOG.debug("shutting down jetty on port {}", m_config.port());
        try {
            m_server.stop();
        } catch (final InterruptedException e) {
            LOG.debug("Interrupted while attempting to shut down Jetty, propagating interrupt and trying again.", e);
            Thread.currentThread().interrupt();
            m_server.stop();
        } catch (final RuntimeException e) {
            LOG.debug("An exception occurred while attempting to shut down Jetty.", e);
            m_server.stop();
            throw e;
        }
    }

