    /**
     * Generate an AssertionFailedError with the specified cause.
     *
     * @param message error message
     * @param t java.lang.Throwable that caused this error to be thrown
     * @throws junit.framework.AssertionFailedError always thrown.  Generated based on the
     * parameters passed.
     */
    public void fail(String message, Throwable t) throws AssertionFailedError {
        AssertionFailedError error = new AssertionFailedError(message);
        error.initCause(t);
        throw error;
    }

