    B compute(A a) throws Exception;

